[[steps]]
name = "Build for linux"
os = "linux"
run = "cargo build --release --locked --target x86_64-unknown-linux-gnu"

[[steps]]
name = "Build for mac"
os = "macos"
run = "cargo build --release --locked"
