env = [
  {name = "IMAGE_DOMAIN", value = "fioncat"}
]

[[steps]]
name = "Get current tag"
run = "git describe --tags --exact-match --abbrev=0"
allow_failure = true
capture_output = "IMAGE_TAG"

[[steps]]
name = "Get commit id"
condition = [
  {env = "IMAGE_TAG", exists = false}
]
run = "echo dev-$(git rev-parse --short HEAD)"
capture_output = "IMAGE_TAG"

[[steps]]
name = "Set image name"
set_env = {name = "IMAGE_NAME", value = "${IMAGE_DOMAIN}/roxide:${IMAGE_TAG}"}

[[steps]]
name = "Show image name"
run = "echo Image is: ${IMAGE_NAME:?}"
