default:
  import:
    - build
    - build-image
    - push-image

build:
  steps:
    - name: Build in docker
      image: "messense/rust-musl-cross:x86_64-musl"
      run: git config --global --add safe.directory /work; cargo build --release --locked --target x86_64-unknown-linux-musl

get-image-name:
  env:
    - name: IMAGE_DOMAIN
      value: "fioncat"
  steps:
    - name: Get tag
      run: git describe --tags --abbrev=0
      capture_output: IMAGE_TAG

    - name: Set image name
      set_env:
        name: IMAGE_NAME
        value: "${IMAGE_DOMAIN:?}/roxide:${IMAGE_TAG:?}"

build-image:
  import: ["get-image-name"]
  steps:
    - name: Build docker image
      docker_build:
        image: "${IMAGE_NAME:?}"
        file: "Dockerfile"

push-image:
  import: ["get-image-name"]
  steps:
    - name: Push docker image
      docker_push: "${IMAGE_NAME:?}"

clean:
  steps:
    - name: Remove old build
      run: rm -rf ./target
