default:
  steps:
    - name: Build in docker
      image: "messense/rust-musl-cross:x86_64-musl"
      run: git config --global --add safe.directory /work; cargo build --release --locked --target x86_64-unknown-linux-musl

    - name: Get tag
      run: git describe --tags --abbrev=0
      capture_output: BUILD_TAG

    - name: Build docker image
      run: sudo docker build -f Dockerfile -t fioncat/roxide:${BUILD_TAG} .

    - name: Push docker image
      run: sudo docker push fioncat/roxide:${BUILD_TAG}

clean:
  steps:
    - name: Remove old build
      run: rm -rf ./target
