[package]
name = "roxide"
version = "0.9.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/roxide"
description = "🎁 A great and fast tool to manage your git repositories"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
chrono = "0.4.30"
clap = { version = "4.4.2", features = ["derive"] }
console = "0.15.7"
dialoguer = "0.10.4"
file-lock = "2.1.10"
num_cpus = "1.16.0"
open = "5.0.0"
# We need this to let cargo build can run in Github workflow.
# Otherwise, the compile will fail because workflow missing openssl dependency.
openssl = { version = "0.10.57", features = ["vendored"] }
pad = "0.1.6"
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
scanf = "1.2.1"
semver = "1.0.18"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
serde_yaml = "0.9.25"
shellexpand = "3.1.0"
strum = { version = "0.25.0", features = ["derive"] }
urlencoding = "2.1.3"

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "8.2.4", features = [ "build", "rustc" ] }

[dev-dependencies]
serial_test = "2.0.0"
