[package]
name = "roxide"
version = "0.10.6"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/roxide"
description = "🎁 A simple and fast tool to manage your git repositories"

[features]
# If your build or runtime environment lacks the openssl dependency, you can enable
# this feature to statically compile openssl into the binary.
# The side effects include an increase in the binary size and a slowdown in the
# compilation speed.
# See: https://docs.rs/openssl/latest/openssl/#vendored
openssl-vendored = ["reqwest/native-tls-vendored"]

[dependencies.reqwest]
version = "0.11.23"
features = [
  "blocking",
  "json",
]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.79"
base64 = "0.21.7"
bincode = "1.3.3"
chrono = "0.4.33"
clap = { version = "4.4.18", features = ["derive"] }
console = "0.15.8"
dialoguer = "0.11.0"
file-lock = "2.1.10"
num_cpus = "1.16.0"
open = "5.0.1"
pad = "0.1.6"
pbkdf2 = "0.12.2"
regex = "1.10.3"
rpassword = "7.3.1"
scanf = "1.2.1"
semver = "1.0.21"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
sha2 = "0.10.8"
shellexpand = "3.1.0"
strum = { version = "0.26.1", features = ["derive"] }
termion = "3.0.0"
urlencoding = "2.1.3"

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "8.3.1", features = [ "build", "rustc" ] }

[profile.release]
lto = true
strip = true
incremental = false
