[package]
name = "roxide"
version = "0.3.0"
edition = "2021"
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/roxide"
description = "🎁 A great and fast tool to manage your git repositories"

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
clap = { version = "4.3.2", features = ["derive"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
shellexpand = "3.1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
# We need this to let cargo build can run in Github workflow.
# Otherwise, the compile will fail because workflow missing openssl dependency.
openssl = { version = "0.10.55", features = ["vendored"] }
urlencoding = "2.1.2"
dialoguer = "0.10.4"
console = "0.15.7"
regex = "1.8.3"
chrono = "0.4.26"
open = "4.1.0"
pad = "0.1.6"
file-lock = "2.1.9"
num_cpus = "1.16.0"
