[package]
name = "roxide"
version = "0.15.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/roxide"
description = "🎁 A simple and fast tool to manage your git repositories"

[features]
# If your build or runtime environment lacks the openssl dependency, you can enable
# this feature to statically compile openssl into the binary.
# The side effects include an increase in the binary size and a slowdown in the
# compilation speed.
# See: https://docs.rs/openssl/latest/openssl/#vendored
openssl-vendored = ["reqwest/native-tls-vendored"]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.82"
base64 = "0.22.0"
bincode = "1.3.3"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
console = "0.15.8"
dialoguer = "0.11.0"
file-lock = "2.1.11"
num_cpus = "1.16.0"
open = "5.0.1"
pad = "0.1.6"
pbkdf2 = "0.12.2"
regex = "1.10.3"
reqwest = { version = "0.12.3", features = ["blocking", "json"] }
rpassword = "7.3.1"
scanf = "1.2.1"
semver = "1.0.22"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
sha2 = "0.10.8"
shellexpand = "3.1.0"
strum = { version = "0.26.2", features = ["derive"] }
termion = "3.0.0"
toml = "0.8.12"
urlencoding = "2.1.3"

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "8.3.1", features = ["build", "rustc"] }

[profile.release]
lto = true
strip = true
incremental = false
