[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture arm",
    "apt-get update && apt-get install --assume-yes libssl-dev:arm"
]
