# A local remote without a "clone" field means that we cannot perform
# operations such as cloning or calling APIs on this remote. Typically, it
# represents a local test remote.
[owners.rust]
on_create = ["cargo"]

[owners.golang]
on_create = ["go-module"]
