# The working directory, where all repo will be stored.
workspace = "~/dev"

# Store some meta data of repo, including database, cache, etc.
metadir = "~/.local/share/roxide"

# The generated command name, to support terminal navigation.
cmd = "rox"

# The tag release rule.
[release]
patch = "v{0}.{1}.{2+}"
minor = "v{0}.{1+}.0"
major = "v{0+}.0.0"
date-stash = "{%Y}-{%m}-{%d}"
date-dor = "{%Y}.{%m}.{%d}"
