workspace: "${PWD}/_test/main/workspace"
metadir: "${PWD}/_test/main/meta"

cmd: "test-rox"

remotes:
  github:
    clone: "github.com"
    user: "fioncat"
    email: "lazycat7706@gmail.com"
    ssh: false
    labels: ["sync"]
    provider: "github"
    token: "${GITHUB_TOKEN}"

    owners:
      fioncat:
        labels: ["pin"]
        ssh: true

      kubernetes:
        alias: "k8s"
        labels: ["k8s"]
        repo_alias:
          kubernetes: "k8s"

  test:
    owners:
      golang:
        on_create: ["golang"]
      rust:
        on_create: ["rust"]

workflows:
  golang:
  - name: main.go
    file: |
      package main

      import "fmt"

      func main() {
      \tfmt.Println("hello, world!")
      }
  - name: go module
    run: go mod init ${REPO_NAME}

  rust:
  - name: init cargo
    run: cargo init

  fetch:
  - name: fetch git
    run: git fetch --all
