icon = "T"

[owners."golang"]
on_create = [
    "go mod init ${REPO_OWNER}/${REPO_NAME}",
    "touch main.go",
    "echo 'package main' > main.go",
    "echo '' >> main.go",
    "echo 'func main() {' >> main.go",
    "echo '}' >> main.go"
]

[owners."rust"]
on_create = ["cargo init"]
