name: cargo-test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install fzf
        run: sudo apt-get install fzf

      - name: Cargo Test
        run: cargo test
